### ISSUE TITLE
Ability to emit fields as tags to InfluxDB

### ISSUE THREAD

**Issue by vito** [hybris/riemann-boshrelease#5]
Hi there, we forked this release a while back to get things going quickly as we were still figuring out our metrics usage patterns in Concourse.

The main pattern we landed on was this:

For all metrics emitted, only use Riemann `tags` for things that we'd want to use for filtering in Riemann, and otherwise use custom fields for everything, as they're much more flexible (being key-value rather than an arbitrary array of strings).

We also had Riemann configured to do the following:
- For every event, convert all custom fields to tags and send them off to InfluxDB.
- For every event, convert all custom fields to `key:value` tag pairs and send them off to Datadog.

Our resulting config can be found here:

https://github.com/xoebus/riemann-boshrelease/blob/master/jobs/riemann/templates/config/riemann.config.erb

Looking back on your release now, while it does support configuring an InfluxDB host, it doesn't seem to do anything about custom fields and tagging. Our approach also is kind of hacky and relies on constructing a new InfluxDB client every time we receive an event, but I'm not sure which would be easiest to work with.

Does our metrics usage pattern align with yours? I wonder if that could just be the generic default, and the same thing could carry over if/when we do a pull request to support configuring Datadog.

**Comment by maksd** [comment]
Hi @vito,
sorry for the late answer. Unfortunately InfluxDB integration was just a test for us back then, we don't really use it right now. But since we had to refactor our release completely to be more generic, then we integrated your InfluxDB code in there, hopefully it will be generic enough for you to use.

Thanks

**Comment by vito** [comment]
Cool, thanks! Glad the release is more generic now too.
